# Generated by Django 6.0.3 on 2026-03-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institute_logos/'),
        ),
        migrations.AddField(
            model_name='institute',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='primary_color',
            field=models.CharField(default='#2196F3', max_length=20),
        ),
        migrations.AddField(
            model_name='institute',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
